name: WinMacBuild

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  Build:
    strategy:
      matrix:
        os: [windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    - name: Initialize submodules
      run: git submodule update --recursive --init

    - name: Make Build Directory
      run: cmake -E make_directory build.common

    # configuration for Windows
    - name: CMake@Win
      if: matrix.os == 'windows-latest'
      working-directory: build.common
      run: >-
        cmake
        ..
    # configuration for Mac
    - name: CMake@MacOS
      if: matrix.os  == 'macOS-latest'
      working-directory: build.common
      run: >-
        cmake
        ..
    - name: Build
      run: cmake --build build.common -j3
